/**
 * Voice registry — the 27 MiniMax voices, hand-authored with persona +
 * use-case metadata so each one is "best money can buy" instead of
 * a one-line "Confident woman" label.
 *
 * Source: MiniMax Speech 2.6 Turbo via Replicate. The `miniMaxVoiceId`
 * field maps to the values in `supabase/functions/generate-voice` →
 * VOICE_MAP. Frontend `id` matches the keys the edge function accepts.
 */
import type { VoiceBlueprint } from "./blueprint";

export const VOICE_BLUEPRINTS: VoiceBlueprint[] = [
  // ─── PROFESSIONAL & CORPORATE ──────────────────────────────────
  {
    id: "nova",
    name: "Nova",
    persona: "Confident corporate trainer · trusted voice of authority",
    bio: "Nova carries the room from the first word. Crisp, confident, and unhurried, she's the voice you reach for when the content needs to land — boardroom, lecture hall, or product launch. Sounds like the person who runs the meeting, never the one who takes notes.",
    miniMaxVoiceId: "English_ConfidentWoman",
    group: "professional", gender: "female", ageRange: "adult",
    accent: "american-neutral", pacing: "measured", emotionalDefault: "confident",
    useCases: ["corporate-training", "course-narration", "presentation", "explainer"],
    sampleShort: "Welcome to today's training. Let's get into it.",
    sampleLong: "Welcome to today's training session. By the end of this video, you'll know exactly what to do — and more importantly, why it matters.",
    isFeatured: true,
  },
  {
    id: "claire",
    name: "Claire",
    persona: "Executive coach · mature professional with gravitas",
    bio: "Claire is the boss your boss wants to be. Calm, decisive, and rich with experience — she delivers strategy briefings, board updates, and high-stakes course material with the kind of poise that makes people lean in.",
    miniMaxVoiceId: "English_MatureBoss",
    group: "professional", gender: "female", ageRange: "mature",
    accent: "american-neutral", pacing: "measured", emotionalDefault: "confident",
    useCases: ["corporate-training", "presentation", "course-narration", "explainer"],
    sampleShort: "Let's review what we covered and what comes next.",
    sampleLong: "Let's review what we covered. Three things to remember, two action items to take, and one question that should sit with you until tomorrow.",
  },
  {
    id: "michael",
    name: "Michael",
    persona: "Trustworthy male trainer · steady, reliable, no-nonsense",
    bio: "Michael is the senior engineer who actually explains things well. He doesn't dress it up — just lays it out clearly, in order, so you can follow along. The voice you trust because he sounds like he's done this a thousand times.",
    miniMaxVoiceId: "English_Trustworth_Man",
    group: "professional", gender: "male", ageRange: "adult",
    accent: "american-neutral", pacing: "natural", emotionalDefault: "confident",
    useCases: ["corporate-training", "product-demo", "explainer", "course-narration"],
    sampleShort: "Here's how this works. Walk with me.",
    sampleLong: "Here's how this works. We'll start with the basics, build up to the edge cases, and by the end you'll be able to explain it back to me.",
  },
  {
    id: "david",
    name: "David",
    persona: "Patient mentor · thoughtful and unhurried",
    bio: "David never rushes you. He's the voice for material that needs time to sink in — onboarding, compliance, sensitive policy work — where the worst thing you can do is sound like you're racing to the end.",
    miniMaxVoiceId: "English_PatientMan",
    group: "professional", gender: "male", ageRange: "mature",
    accent: "american-neutral", pacing: "slow", emotionalDefault: "calm",
    useCases: ["corporate-training", "course-narration", "explainer"],
    sampleShort: "Take a breath. We'll get there together.",
    sampleLong: "Take a breath. Read the slide once, then read it again. We'll get there together — there's no race here.",
  },
  {
    id: "james",
    name: "James",
    persona: "Debater · sharp, structured, argumentative",
    bio: "James thinks out loud — but in paragraphs, not bullet points. He's built for content where you're actually defending a position: opinion pieces, persuasive essays, thought-leadership keynotes.",
    miniMaxVoiceId: "English_Debator",
    group: "professional", gender: "male", ageRange: "adult",
    accent: "british-rp", pacing: "punchy", emotionalDefault: "confident",
    useCases: ["presentation", "explainer", "documentary"],
    sampleShort: "Here's the thing — and I'll defend this — it's not optional.",
    sampleLong: "Here's the thing. And I'll defend this position to anyone who'll listen: the old way isn't slower, it isn't safer, and it certainly isn't cheaper.",
  },
  {
    id: "victoria",
    name: "Victoria",
    persona: "Imposing executive · commands the room",
    bio: "Victoria walks in and the conversation changes. Use her for prestige content — keynotes, brand films, the kind of training video that's also a recruitment tool. She doesn't ask for attention. She has it.",
    miniMaxVoiceId: "English_ImposingManner",
    group: "professional", gender: "female", ageRange: "mature",
    accent: "british-rp", pacing: "measured", emotionalDefault: "confident",
    useCases: ["presentation", "trailer", "ad-spot", "course-narration"],
    sampleShort: "What you're about to see changes how the work gets done.",
    sampleLong: "What you're about to see changes how the work gets done. Pay attention — because in six months, this will be the new normal.",
  },
  {
    id: "shimmer",
    name: "Shimmer",
    persona: "Wise mentor · the quiet authority everyone respects",
    bio: "Shimmer is the elder stateswoman of the catalog. Warmth wrapped around wisdom — she's the voice for legacy content, founder stories, retirement-celebration speeches, and any piece where the weight of experience is the point.",
    miniMaxVoiceId: "English_Wiselady",
    group: "professional", gender: "female", ageRange: "senior",
    accent: "american-warm", pacing: "slow", emotionalDefault: "warm",
    useCases: ["documentary", "audiobook", "course-narration"],
    sampleShort: "In all my years, I've learned one thing — listen first.",
    sampleLong: "In all my years, I've learned one thing about leading well. Listen first. Speak less. And when you do speak, mean every word.",
  },

  // ─── CONVERSATIONAL & WARM ──────────────────────────────────────
  {
    id: "echo",
    name: "Echo",
    persona: "Gentle male host · podcast-warm and intimate",
    bio: "Echo sounds like he's talking just to you. Soft on consonants, never pushy, perfect for content that lives or dies on warmth — meditation prompts, wellness explainers, intro-to-anything courses.",
    miniMaxVoiceId: "English_Gentle-voiced_man",
    group: "conversational", gender: "male", ageRange: "adult",
    accent: "american-warm", pacing: "natural", emotionalDefault: "warm",
    useCases: ["podcast-intro", "vlog-vo", "course-narration"],
    sampleShort: "Hey — glad you're here. Let's take it slow.",
    sampleLong: "Hey. Glad you're here. We're not going to rush anything today. Just settle in, get comfortable, and we'll walk through this together.",
    isFeatured: true,
  },
  {
    id: "tyler",
    name: "Tyler",
    persona: "Friendly guy · easygoing American buddy energy",
    bio: "Tyler is the guy you'd grab lunch with. Warm but not soft, casual but not sloppy — best for content where you want the audience to feel like they're getting tips from a friend, not instructions from a manager.",
    miniMaxVoiceId: "English_FriendlyPerson",
    group: "conversational", gender: "male", ageRange: "young-adult",
    accent: "american-warm", pacing: "natural", emotionalDefault: "warm",
    useCases: ["vlog-vo", "social-vo", "product-demo", "explainer"],
    sampleShort: "Okay so here's a thing that took me forever to figure out.",
    sampleLong: "Okay so here's a thing that took me forever to figure out. And I'm just going to save you the time by telling you straight up, this is the trick.",
  },
  {
    id: "bella",
    name: "Bella",
    persona: "Upbeat woman · sunny morning-show host",
    bio: "Bella is the friend who makes your day better by walking into the room. Bright, optimistic, full of forward energy — built for onboarding flows, welcome videos, and any time you need the room to lean in.",
    miniMaxVoiceId: "English_Upbeat_Woman",
    group: "conversational", gender: "female", ageRange: "young-adult",
    accent: "american-warm", pacing: "natural", emotionalDefault: "joyful",
    useCases: ["vlog-vo", "social-vo", "product-demo", "ad-spot"],
    sampleShort: "Hi there — so excited you're here today.",
    sampleLong: "Hi there. So excited you're here today, because we have a ton of cool stuff to walk through, and honestly? You're going to love this.",
  },
  {
    id: "sarah",
    name: "Sarah",
    persona: "Calm woman · soothing voice for tense content",
    bio: "Sarah is the voice you put in front of a panicking learner. Even, unflappable, soft when it needs to be — best for compliance, crisis training, mental-wellness onboarding, anything where the audience is already on edge.",
    miniMaxVoiceId: "English_CalmWoman",
    group: "conversational", gender: "female", ageRange: "adult",
    accent: "american-neutral", pacing: "slow", emotionalDefault: "calm",
    useCases: ["course-narration", "explainer", "audiobook"],
    sampleShort: "Let's slow down for a moment and think this through.",
    sampleLong: "Let's slow down for a moment and think this through. There's no urgency here — just one decision at a time, and we have all the time we need.",
  },
  {
    id: "alloy",
    name: "Alloy",
    persona: "Serene woman · ethereal and reassuring",
    bio: "Alloy floats above the noise. She's almost meditative — perfect for ASMR-style explainers, art-history voiceovers, or any premium content where the voice itself should feel like a luxury.",
    miniMaxVoiceId: "English_SereneWoman",
    group: "conversational", gender: "female", ageRange: "adult",
    accent: "american-warm", pacing: "slow", emotionalDefault: "calm",
    useCases: ["audiobook", "documentary", "course-narration"],
    sampleShort: "Close your eyes for a second and just listen.",
    sampleLong: "Close your eyes for a second and just listen. Notice the rhythm of your breath. We're going to use this calm as the starting point.",
  },
  {
    id: "emma",
    name: "Emma",
    persona: "Kind-hearted girl · sweet without being saccharine",
    bio: "Emma is the friend who actually remembers your birthday. Warm, kind, lightly playful — best for content with an emotional core: scholarship announcements, charity asks, family-product walkthroughs.",
    miniMaxVoiceId: "English_Kind-heartedGirl",
    group: "conversational", gender: "female", ageRange: "young-adult",
    accent: "american-warm", pacing: "natural", emotionalDefault: "warm",
    useCases: ["vlog-vo", "course-narration", "explainer"],
    sampleShort: "I know this looks like a lot — let's break it down.",
    sampleLong: "I know this looks like a lot. Take a breath. We're going to break this down into really small pieces, and I promise it'll all make sense.",
  },
  {
    id: "lily",
    name: "Lily",
    persona: "Graceful lady · refined and luminous",
    bio: "Lily is the voice for prestige consumer brands. She has a quiet elegance that makes anything she narrates feel a tier nicer than it is — fragrance ads, art-gallery audio guides, high-end course intros.",
    miniMaxVoiceId: "English_Graceful_Lady",
    group: "conversational", gender: "female", ageRange: "mature",
    accent: "british-modern", pacing: "measured", emotionalDefault: "warm",
    useCases: ["ad-spot", "documentary", "audiobook", "trailer"],
    sampleShort: "Some things take time. This is one of them.",
    sampleLong: "Some things take time. This is one of them. Made slowly, considered carefully, given to you the way it deserves to be given.",
  },
  {
    id: "charlotte",
    name: "Charlotte",
    persona: "Sentimental lady · tender and emotional",
    bio: "Charlotte cries at the credits. Use her for content that's allowed to feel — memoirs, family histories, anniversary brand films, anything where holding back would betray the material.",
    miniMaxVoiceId: "English_SentimentalLady",
    group: "conversational", gender: "female", ageRange: "mature",
    accent: "british-modern", pacing: "slow", emotionalDefault: "warm",
    useCases: ["audiobook", "documentary", "drama"],
    sampleShort: "I want to tell you a story that took twenty years to tell.",
    sampleLong: "I want to tell you a story that took twenty years to tell. It's not a long story, but every word in it has been waiting for the right moment.",
  },

  // ─── ENERGETIC & UPBEAT ─────────────────────────────────────────
  {
    id: "marcus",
    name: "Marcus",
    persona: "Decent young man · bright-eyed millennial",
    bio: "Marcus is the new hire who already knows how to deliver. Punchy, optimistic, fast on his feet — best for high-energy product demos, app walkthroughs, and any TikTok where attention dies in three seconds.",
    miniMaxVoiceId: "English_DecentYoungMan",
    group: "energetic", gender: "male", ageRange: "young-adult",
    accent: "american-energetic", pacing: "punchy", emotionalDefault: "joyful",
    useCases: ["social-vo", "vlog-vo", "product-demo", "ad-spot"],
    sampleShort: "Watch this — three seconds and you'll see why.",
    sampleLong: "Watch this. Three seconds, that's all I need. See what just happened? Now imagine that in your workflow, every single day.",
  },
  {
    id: "jake",
    name: "Jake",
    persona: "Strong-willed boy · scrappy and persuasive",
    bio: "Jake doesn't take no for an answer. He's built for sales-ad scripts, gym-promo voiceovers, the kind of content that needs to hit the audience in the chest and not let go.",
    miniMaxVoiceId: "English_Strong-WilledBoy",
    group: "energetic", gender: "male", ageRange: "young-adult",
    accent: "american-energetic", pacing: "punchy", emotionalDefault: "intense",
    useCases: ["ad-spot", "sales-pitch", "trailer"],
    sampleShort: "You're going to want to see this. Trust me.",
    sampleLong: "You're going to want to see this. Trust me. Forget what you thought you knew about the category — this changes the whole game.",
  },
  {
    id: "jessica",
    name: "Jessica",
    persona: "Radiant girl · sunshine in audio form",
    bio: "Jessica is pure sparkle. She makes every line sound like it's being said for the first time, with the kind of energy that fits beauty walkthroughs, college-tour videos, lifestyle vlogs.",
    miniMaxVoiceId: "English_radiant_girl",
    group: "energetic", gender: "female", ageRange: "young-adult",
    accent: "american-energetic", pacing: "punchy", emotionalDefault: "joyful",
    useCases: ["vlog-vo", "social-vo", "ad-spot", "product-demo"],
    sampleShort: "Hi babes — wait until you see what I'm about to show you.",
    sampleLong: "Hi babes! Wait until you see what I'm about to show you, because honestly, I'm still freaking out about how good this came out.",
  },
  {
    id: "zoey",
    name: "Zoey",
    persona: "Playful girl · mischief and charm",
    bio: "Zoey is the friend who makes everyone laugh. Light, mischievous, ready with a quick aside — perfect for explainer videos with a comedy bent, game-tutorial voiceovers, content that doesn't take itself seriously.",
    miniMaxVoiceId: "English_PlayfulGirl",
    group: "energetic", gender: "female", ageRange: "young-adult",
    accent: "american-energetic", pacing: "natural", emotionalDefault: "playful",
    useCases: ["vlog-vo", "social-vo", "explainer"],
    sampleShort: "Okay this is kind of dumb but it actually works.",
    sampleLong: "Okay this is kind of dumb but it actually works. I tried it once as a joke, and now? Now it's my whole personality. You're welcome.",
  },
  {
    id: "mia",
    name: "Mia",
    persona: "Lovely girl · sweet, peppy, approachable",
    bio: "Mia is the voice of a brand that wants you to like it. She sounds like the influencer your daughter follows — relatable, polished, and just a touch aspirational.",
    miniMaxVoiceId: "English_LovelyGirl",
    group: "energetic", gender: "female", ageRange: "young-adult",
    accent: "american-warm", pacing: "natural", emotionalDefault: "joyful",
    useCases: ["vlog-vo", "social-vo", "ad-spot"],
    sampleShort: "I'm not going to gatekeep this — here's exactly how I did it.",
    sampleLong: "I'm not going to gatekeep this. Here's exactly how I did it, step by step, including the embarrassing parts I almost edited out.",
  },

  // ─── AUTHORITATIVE & COMMANDING ─────────────────────────────────
  {
    id: "onyx",
    name: "Onyx",
    persona: "Deep male voice · the trailer voice of God",
    bio: "Onyx is the voice. The one you hire when the script starts with 'In a world…' Cinematic, weighty, capable of making any sentence sound like the most important thing you've heard all year.",
    miniMaxVoiceId: "English_ManWithDeepVoice",
    group: "authoritative", gender: "male", ageRange: "mature",
    accent: "neutral-cinematic", pacing: "slow", emotionalDefault: "intense",
    useCases: ["trailer", "ad-spot", "documentary", "drama"],
    sampleShort: "In every life, there is a moment that changes everything.",
    sampleLong: "In every life, there is a moment that changes everything. A single decision, made in a single breath, that draws the line between who you were and who you become.",
    isFeatured: true,
  },
  {
    id: "george",
    name: "George",
    persona: "Deep-voiced gentleman · classical and commanding",
    bio: "George is the British baritone every period drama wants. Old-school authority with a velvet finish — best for prestige documentaries, museum audio guides, anything where you want to sound like the BBC ran the project.",
    miniMaxVoiceId: "English_Deep-VoicedGentleman",
    group: "authoritative", gender: "male", ageRange: "mature",
    accent: "british-rp", pacing: "slow", emotionalDefault: "confident",
    useCases: ["documentary", "audiobook", "drama", "trailer"],
    sampleShort: "It began, as these things often do, with a single letter.",
    sampleLong: "It began, as these things often do, with a single letter — written in a moment of confusion, posted in haste, and read at exactly the wrong dinner table.",
  },
  {
    id: "aria",
    name: "Aria",
    persona: "Assertive queen · regal and unyielding",
    bio: "Aria sits on a throne and you walk up to her. Built for women-led brand films, executive-coaching content, athletics-brand campaigns — anywhere you need to project unmistakable authority without raising a voice.",
    miniMaxVoiceId: "English_AssertiveQueen",
    group: "authoritative", gender: "female", ageRange: "adult",
    accent: "british-rp", pacing: "measured", emotionalDefault: "confident",
    useCases: ["trailer", "ad-spot", "documentary", "presentation"],
    sampleShort: "I'm not asking. I'm telling you how this is going to go.",
    sampleLong: "I'm not asking. I'm telling you how this is going to go. We're not going to argue about it, we're not going to revisit it tomorrow — we are simply going to do it, and do it well.",
  },

  // ─── NARRATIVE & STORYTELLING ───────────────────────────────────
  {
    id: "adam",
    name: "Adam",
    persona: "Expressive narrator · animated and evocative",
    bio: "Adam pulls listeners through a story. He varies pace and pitch beautifully — best for audiobooks with multiple characters, kids' content, dramatic readings of historical material.",
    miniMaxVoiceId: "English_expressive_narrator",
    group: "narrative", gender: "male", ageRange: "adult",
    accent: "american-warm", pacing: "natural", emotionalDefault: "playful",
    useCases: ["audiobook", "documentary", "drama"],
    sampleShort: "Once upon a time — and I do mean once — there was a city that forgot itself.",
    sampleLong: "Once upon a time — and I do mean once — there was a city that forgot itself. It didn't happen all at once. It happened the way these things always do: slowly, then all at once.",
  },
  {
    id: "fable",
    name: "Fable",
    persona: "Captivating storyteller · the voice around the campfire",
    bio: "Fable is the friend who tells stories so well you forget your phone is in your pocket. Best for podcasts, fairy-tale anthologies, brand origin stories that need to feel handmade.",
    miniMaxVoiceId: "English_CaptivatingStoryteller",
    group: "narrative", gender: "male", ageRange: "adult",
    accent: "american-warm", pacing: "measured", emotionalDefault: "contemplative",
    useCases: ["audiobook", "podcast-intro", "documentary", "drama"],
    sampleShort: "Let me tell you something I haven't told anyone in years.",
    sampleLong: "Let me tell you something I haven't told anyone in years. Not because it's a secret — it's not — but because nobody's ever asked the right question to bring it out.",
    isFeatured: true,
  },
  {
    id: "documentary",
    name: "Scholar",
    persona: "Wise scholar · documentary VO with intellectual weight",
    bio: "Scholar narrates the documentary you'd see on a Sunday night and end up watching all the way through. Measured, thoughtful, capable of carrying long stretches of dense material without losing the listener.",
    miniMaxVoiceId: "English_WiseScholar",
    group: "narrative", gender: "male", ageRange: "mature",
    accent: "british-rp", pacing: "measured", emotionalDefault: "contemplative",
    useCases: ["documentary", "course-narration", "audiobook"],
    sampleShort: "Consider, for a moment, what we mean when we say 'progress.'",
    sampleLong: "Consider, for a moment, what we mean when we say 'progress.' Whose progress, exactly. Measured against what. And paid for — let us not forget this part — by whom.",
  },
  {
    id: "rachel",
    name: "Rachel",
    persona: "Anime narrator · dynamic and theatrical",
    bio: "Rachel is the voice that opens an anime series. Bright, dynamic, switches between intimate and epic in the same breath — best for animated content, character-driven explainers, anything that wants a touch of theater.",
    miniMaxVoiceId: "English_AnimeCharacter",
    group: "narrative", gender: "female", ageRange: "young-adult",
    accent: "american-energetic", pacing: "natural", emotionalDefault: "joyful",
    useCases: ["drama", "vlog-vo", "social-vo"],
    sampleShort: "It was the day everything changed — and nobody saw it coming.",
    sampleLong: "It was the day everything changed — and nobody saw it coming. Not the council, not the elders, not even the protagonist herself. But change had already chosen its hour.",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// Public API
// ─────────────────────────────────────────────────────────────────────────────
export function getAllVoiceBlueprints(): VoiceBlueprint[] {
  return VOICE_BLUEPRINTS;
}

export function getVoiceBlueprint(id: string): VoiceBlueprint | undefined {
  return VOICE_BLUEPRINTS.find(v => v.id === id);
}
