// ═══════════════════════════════════════════════════════════════════════════
// effect-compiler — the VFX SUPERVISOR agent.
//
// Input: a creative intent in plain language ("someone's Facebook feed with a
// video playing inside it; the person realizes they can crack the screen and
// climb out like a window"). Output: a validated EffectPlan — layers assigned
// per the doctrine, tools chosen from the registry, prompts written, handoffs
// and QC assertions placed. Saved to effect_recipes; runnable by
// effect-executor.
//
// POST { intent, family?, slug?, save? } → { plan, recipeSlug? }
// ═══════════════════════════════════════════════════════════════════════════

import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.39.3';
import { publicErrorMessage } from '../_shared/safe-error.ts';
import { completeLLM } from '../_shared/llm-complete.ts';
import { validateEffectPlan } from '../_shared/effect-plan.ts';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};
const json = (status: number, body: unknown) =>
  new Response(JSON.stringify(body), { status, headers: { ...corsHeaders, 'Content-Type': 'application/json' } });

const SUPERVISOR_PROMPT = `You are a world-class VFX SUPERVISOR compiling a creative intent into an executable EffectPlan for an AI video pipeline.

═══ THE DOCTRINE (non-negotiable) ═══
Every element of an effect is one of three kinds of matter:
• RIGID — UI, screens, feeds, text, logos, HUDs. Video models CANNOT hold pixels still; rigid matter is ALWAYS composited (tool: composite.overlay) or generated as a STILL (image.*) and held.
• ALIVE — people, physics, debris, fire, water, light, atmosphere. Compositing CANNOT fake physics; alive matter is ALWAYS generated by a video model in-scene so lighting/shadows/motion-blur/interaction are rendered by the model itself.
• BRIDGE — the moment rigid becomes alive (a screen cracks, a photo animates). Bridges are built as HANDOFF KEYFRAMES: edit the exact frame with image.kontext or image.nano_banana (identity-preserving), then generate video FROM that keyframe.

═══ THE TOOL REGISTRY ═══
image.nano_banana {prompt, image_input?[], aspect_ratio} — best still generator + reference-guided edits (UI, feeds, composited scenes)
image.kontext {prompt, input_image, aspect_ratio} — identity-preserving edit of an exact frame (crack the screen ON this frame)
image.flux_ultra {prompt, aspect_ratio} — photoreal T2I
video.seedance {prompt, image?, last_frame_image?, reference_images?[], reference_videos?[], duration 2-12, aspect_ratio, camera_fixed, generate_audio, seed} — #1 model; keyframe pairs; reference videos = motion transfer addressed as [Video1] in prompt. RULE: reference_* cannot combine with image/last_frame_image.
video.veo {prompt, image?, last_frame?, duration 4|6|8, generate_audio, negative_prompt} — keyframe-pair interpolation, context-aware audio
video.kling {prompt, start_image?, duration 5|10|15, negative_prompt, generate_audio} — lip-sync class
video.wan_i2v {prompt, image, duration 2-15} — budget i2v
video.motion_control {image, reference_video, orientation} — transfer a performance from reference video to a character image
video.aleph2 {video, prompt, reference_image?} — surgical instruction EDIT of an existing clip (add/remove/relight/restyle)
video.kling_o1 {video, prompt} / video.wan_edit {video, prompt} — alternate instruction editors
matte.sam2 {image} — subject matte; depth.estimate {image} — depth map
frame.extract {video, position:'first'|'last'} — pull exact frames for handoffs
composite.overlay {base(image|video), overlay(image|video), rect[x,y,w,h px], width, height, durationSec} — PIXEL-LOCKED overlay; the only place pixels are pasted
audio.tts {text, voiceId} / audio.music {prompt, duration} / audio.sfx {prompt, duration}

═══ CRAFT RULES ═══
1. Camera: when a rigid layer must appear stable inside a GENERATED shot, set camera_fixed:true and say "locked-off camera" in the prompt.
2. Timing: impacts follow anticipation → strike → follow-through. Put the strike ~20-30% into the clip. Sound lands ON the strike (generate_audio:true, describe the sound in the prompt: "sharp glass crack, then cascading shatter").
3. Physics prompts name mass and consequence: "shards spin with weight, catch light, fall under gravity, bounce once" — never "particles fly".
4. Identity: any recurring person must be pinned — reference the keyframe chain or reference_images, and repeat their exact description verbatim in every prompt.
5. Handoffs: extract the EXACT frame (frame.extract), edit it (image.kontext), generate FROM the edit. Never let the model re-imagine a frame it must continue from.
6. Assertions: give every stage machine-checkable QC — region_rigid for locked UI (with normalized region), identity_hold (with referenceKey), physics_plausible / no_artifacts for effect shots. Write contracts a vision model can judge from frames.
7. {{stageId}} in any input resolves to that stage's output URL; {{stageId.field}} for named fields. Stages run in array order; refs may only point backwards.

═══ OUTPUT ═══
Respond with ONE JSON object — a valid EffectPlan:
{"id":"kebab-slug","name":"...","intent":"<the input verbatim>","family":"breakout|cinematic|ad|social|custom","version":1,
 "stages":[{"id":"...","layer":"rigid|alive|bridge|audio|analysis","tool":"...","purpose":"...","inputs":{...},"assertions":[...],"maxRetries":1}],
 "finalStage":"...","timing":{"impactStage":"...","impactAtSec":1.5}}
No commentary. The plan must be executable exactly as written.`;

serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response(null, { headers: corsHeaders });
  try {
    const { validateAuth, unauthorizedResponse } = await import('../_shared/auth-guard.ts');
    const auth = await validateAuth(req);
    if (!auth.authenticated) return unauthorizedResponse(corsHeaders, auth.error);

    const { intent, family, slug, save } = await req.json();
    if (!intent || String(intent).trim().length < 10) return json(400, { error: 'intent required (plain-language description of the effect)' });

    // S2 fix: GPT-5 planning is real spend. Rate-limit it (authoring tool, low
    // volume; internal service-role callers exempt).
    if (!auth.isServiceRole && auth.userId) {
      const { aiRateLimit } = await import('../_shared/ai-credit-gate.ts');
      const admin = createClient(Deno.env.get('SUPABASE_URL')!, Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);
      const limited = await aiRateLimit({ supabase: admin, fnName: 'effect-compiler', userId: auth.userId, cost: 0, dailyCap: 30, corsHeaders });
      if (limited) return limited;
    }

    // GPT-5 for planning depth; one self-repair pass on validation failure.
    let plan: unknown = null;
    let errors: string[] = [];
    for (let attempt = 0; attempt < 2; attempt++) {
      const r = await completeLLM({
        systemPrompt: SUPERVISOR_PROMPT,
        userPrompt:
          attempt === 0
            ? `INTENT: ${intent}\n${family ? `FAMILY: ${family}\n` : ''}${slug ? `USE SLUG: ${slug}\n` : ''}Compile the EffectPlan.`
            : `INTENT: ${intent}\nYour previous plan failed validation with: ${errors.join('; ')}\nFix and return the corrected EffectPlan JSON.`,
        maxTokens: 6000,
        json: true,
        replicateModel: 'openai/gpt-5',
      });
      try {
        plan = JSON.parse(r.text.match(/\{[\s\S]*\}/)?.[0] ?? r.text);
      } catch {
        errors = ['output was not valid JSON'];
        continue;
      }
      const v = validateEffectPlan(plan);
      if (v.ok) {
        if (save) {
          const supabase = createClient(Deno.env.get('SUPABASE_URL')!, Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);
          await supabase.from('effect_recipes').upsert(
            { slug: v.plan.id, name: v.plan.name, family: v.plan.family ?? 'custom', plan: v.plan, created_by: auth.userId },
            { onConflict: 'slug' },
          );
        }
        return json(200, { plan: v.plan, recipeSlug: save ? v.plan.id : undefined });
      }
      errors = v.errors;
    }
    return json(422, { error: 'supervisor could not produce a valid plan', details: errors, lastPlan: plan });
  } catch (e) {
    console.error('[effect-compiler] error:', e);
    return json(500, { error: publicErrorMessage(e) });
  }
});
