-- Bundle 2: REVOKE EXECUTE from anon on all SECURITY DEFINER functions still exposed.
-- Internal has_role()/auth.uid() guards already block anon at runtime; this is defense-in-depth.

REVOKE EXECUTE ON FUNCTION public.accept_organization_invite(text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.add_org_creator_as_owner() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.add_org_domain(uuid, text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.admin_activate_enterprise_org(uuid, text, text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.admin_bump_security_versions_except(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.admin_change_account_type(uuid, text, text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.admin_create_impersonation_token(uuid, text, integer) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.admin_delete_org(uuid, text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.admin_force_tier(uuid, text, text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.admin_get_email_log(text, integer) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.admin_suspend_account(uuid, text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.admin_transfer_org_owner(uuid, uuid, text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.admin_unsuspend_account(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.assign_org_seat(uuid, uuid, org_role) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.consume_onboarding_intent(text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.create_org_for_user(uuid, text, text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.create_personal_org_for_new_user() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.delete_email(text, bigint) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.enqueue_email(text, jsonb) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.find_org_by_email_domain(text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.fn_log_workspace_event(uuid, text, text, text, text, jsonb) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.fn_org_has_min_role(uuid, uuid, text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.fn_org_member_role(uuid, uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.fn_soft_delete_org(uuid, text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.fn_transfer_ownership(uuid, uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.get_cinema_entitlement(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.get_org_seat_count(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.get_user_org_role(uuid, uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.has_account_type(uuid, text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.has_active_subscription(uuid, text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.has_org_permission(uuid, uuid, org_role) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.is_blocked_business_email(text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.is_org_member(uuid, uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.mark_org_onboarded(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.monthly_org_credit_refill() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.move_to_dlq(text, text, bigint, jsonb) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.notify_org_credits_low() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.notify_org_member_joined() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.notify_org_role_changed() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.protect_last_owner() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.provision_enterprise_org(uuid, uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.read_email_batch(text, integer, integer) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.resolve_sso_for_email(text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.revoke_org_seat(uuid, uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.set_member_credit_limit(uuid, uuid, integer) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.set_org_auto_recharge(uuid, boolean, integer, integer) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.set_org_integration_webhook(uuid, text, text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.set_org_onboarding_override(uuid, text, boolean, text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.set_org_onboarding_override(uuid, text, boolean) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.set_org_plan(uuid, text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.set_org_security_policy(uuid, boolean) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.set_org_spend_alerts(uuid, integer, integer) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.sync_subscription_to_profile() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.sync_video_clips_to_project() FROM anon, public;

-- Bundle 4: ALTER FUNCTION ... SET search_path = public on the 5 still-mutable functions
ALTER FUNCTION public.delete_email(text, bigint) SET search_path = public;
ALTER FUNCTION public.enqueue_email(text, jsonb) SET search_path = public;
ALTER FUNCTION public.fn_touch_updated_at() SET search_path = public;
ALTER FUNCTION public.move_to_dlq(text, text, bigint, jsonb) SET search_path = public;
ALTER FUNCTION public.read_email_batch(text, integer, integer) SET search_path = public;