REVOKE EXECUTE ON FUNCTION public.acquire_generation_lock(uuid, integer, uuid)                                          FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.add_credits(uuid, integer, text, text)                                                FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.add_user_xp(uuid, integer, text)                                                       FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.admin_force_logout_user(uuid)                                                          FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.admin_get_audit_logs(integer, integer)                                                 FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.admin_list_users(integer, integer, text)                                               FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.admin_manage_credit_package(text, uuid, text, integer, integer, boolean, boolean, text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.admin_manage_role(uuid, app_role, text)                                                FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.charge_preproduction_credits(uuid, text, integer)                                      FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.charge_preproduction_credits(uuid, text)                                               FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.charge_preproduction_credits(uuid, uuid, text)                                         FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.check_casting_eligibility()                                                            FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.check_clip_continuity_ready(uuid, integer)                                             FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.check_refund_eligibility(uuid, uuid)                                                   FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.check_support_rate_limit(text)                                                         FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.create_member_joined_activity()                                                        FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.detect_credit_anomaly(uuid, integer)                                                   FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.enforce_admin_lock()                                                                   FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.get_or_create_dm_conversation(uuid)                                                    FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_pipeline_context(uuid)                                                             FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_project_voice_map(uuid)                                                            FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.handle_casting_approval()                                                              FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.increment_widget_analytics(uuid, text)                                                 FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_admin(uuid)                                                                         FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.log_api_cost(uuid, uuid, text, text, text, integer, integer, integer, text, jsonb)     FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.refund_production_credits(uuid, text, text)                                            FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.update_genesis_video_votes()                                                           FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.update_user_streak(uuid)                                                               FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.upsert_video_clip(uuid, uuid, integer, text, text, text, text, text, jsonb, text, integer)  FROM PUBLIC, anon;
